const dummy = {
  id: 'm1',
  matchNumber: 1,
  teamA: 'TEAM 큐베',
  teamB: 'TEAM 뱅',
  scoreA: 0,
  scoreB: 0,
  date: '2025-04-06',
  completed: false,
  sets: [
    {
      id: 's2',
      setNumber: 2,
      winner: '',
      blueTeamBans: ['Varus', 'Ahri', 'Nautilus', 'Galio', 'Malzahar'],
      redTeamBans: ['Lulu', 'Draven', 'Nocturne', 'Sion', 'Viktor'],
      blueTeamPicks: ['MonkeyKing', 'Yuumi', 'Sivir', 'Rumble', 'Sylas'],
      redTeamPicks: ['Sejuani', 'Ezreal', 'Maokai', 'Yone', 'AurelionSol'],
      blueTeamKills: 0,
      redTeamKills: 0,
      blueTeamDeath: 0,
      redTeamDeath: 0,
      blueTeamAsist: 0,
      redTeamAsist: 0,
      blueTeamGold: 0,
      redTeamGold: 0,
      duration: '',
      blueTeam: [
        {
          name: '강소연',
          champion: 'Rumble',
          role: 'TOP',
          kill: 0,
          death: 0,
          assist: 0,
          damage: 0,
          gold: 0,
        },
        {
          name: '네클릿',
          champion: 'MonkeyKing',
          role: 'JG',
          kill: 0,
          death: 0,
          assist: 0,
          damage: 0,
          gold: 0,
        },
        {
          name: '큐베',
          champion: 'Sylas',
          role: 'MID',
          kill: 0,
          death: 0,
          assist: 0,
          damage: 0,
          gold: 0,
        },
        {
          name: '크캣',
          champion: 'Sivir',
          role: 'ADC',
          kill: 0,
          death: 0,
          assist: 0,
          damage: 0,
          gold: 0,
        },
        {
          name: '루루카',
          champion: 'Yuumi',
          role: 'SUP',
          kill: 0,
          death: 0,
          assist: 0,
          damage: 0,
          gold: 0,
        },
      ],
      redTeam: [
        {
          name: '인섹',
          champion: 'Yone',
          role: 'TOP',
          kill: 0,
          death: 0,
          assist: 0,
          damage: 0,
          gold: 0,
        },
        {
          name: '고수달',
          champion: 'Sejuani',
          role: 'JG',
          kill: 0,
          death: 0,
          assist: 0,
          damage: 0,
          gold: 0,
        },
        {
          name: '인간젤리',
          champion: 'AurelionSol',
          role: 'MID',
          kill: 0,
          death: 0,
          assist: 0,
          damage: 0,
          gold: 0,
        },
        {
          name: '뱅',
          champion: 'Ezreal',
          role: 'ADC',
          kill: 0,
          death: 0,
          assist: 0,
          damage: 0,
          gold: 0,
        },
        {
          name: '던',
          champion: 'Maokai',
          role: 'SUP',
          kill: 0,
          death: 0,
          assist: 0,
          damage: 0,
          gold: 0,
        },
      ],
    },
  ],
}

export { dummy }
