import { IMatch } from '@/types'

const totalMatchData: IMatch[] = [
  {
    id: 'm1',
    matchNumber: 1,
    blueTeam: 'TEAM 큐베',
    redTeam: 'TEAM 뱅',
    blueTeamScore: 0,
    redTeamScore: 0,
    date: '2025-04-06',
    completed: false,
    stage: '리그전',
    sets: [
      {
        id: 's1',
        setNumber: 1,
        winner: 'TEAM 큐베',
        blueTeamBans: ['Annie', 'Annie', 'Annie', 'Annie', 'Annie'],
        redTeamBans: ['Annie', 'Annie', 'Annie', 'Annie', 'Annie'],
        blueTeamPicks: ['Annie', 'Annie', 'Annie', 'Annie', 'Annie'],
        redTeamPicks: ['Annie', 'Annie', 'Annie', 'Annie', 'Annie'],
        blueTeamKills: 0,
        redTeamKills: 0,
        blueTeamDeath: 0,
        redTeamDeath: 0,
        blueTeamAsist: 0,
        redTeamAsist: 0,
        blueTeamGold: 8,
        redTeamGold: 8,
        duration: '35:20',
        blueTeam: [
          {
            name: '플레임',
            role: 'TOP',
            champion: 'Annie',
            kill: 0,
            death: 0,
            assist: 0,
            damage: 0,
            gold: 0,
          },
          {
            name: '소우릎',
            role: 'JG',
            champion: 'Annie',
            kill: 0,
            death: 0,
            assist: 0,
            damage: 0,
            gold: 0,
          },
          {
            name: '헤징',
            role: 'MID',
            champion: 'Annie',
            kill: 0,
            death: 0,
            assist: 0,
            damage: 0,
            gold: 0,
          },
          {
            name: '러너',
            role: 'ADC',
            champion: 'Annie',
            kill: 0,
            death: 0,
            assist: 0,
            damage: 0,
            gold: 0,
          },
          {
            name: '눈꽃',
            role: 'SUP',
            champion: 'Annie',
            kill: 0,
            death: 0,
            assist: 0,
            damage: 0,
            gold: 0,
          },
        ],
        redTeam: [
          {
            name: '룩삼',
            role: 'TOP',
            champion: 'Annie',
            kill: 0,
            death: 0,
            assist: 0,
            damage: 0,
            gold: 0,
          },
          {
            name: '앰비션',
            role: 'JG',
            champion: 'Annie',
            kill: 0,
            death: 0,
            assist: 0,
            damage: 0,
            gold: 0,
          },
          {
            name: '실프',
            role: 'MID',
            champion: 'Annie',
            kill: 0,
            death: 0,
            assist: 0,
            damage: 0,
            gold: 0,
          },
          {
            name: '따효니',
            role: 'ADC',
            champion: 'Annie',
            kill: 0,
            death: 0,
            assist: 0,
            damage: 0,
            gold: 0,
          },
          {
            name: '라콩',
            role: 'SUP',
            champion: 'Annie',
            kill: 0,
            death: 0,
            assist: 0,
            damage: 0,
            gold: 0,
          },
        ],
      },
      {
        id: 's1',
        setNumber: 2,
        winner: 'TEAM 큐베',
        blueTeamBans: ['Annie', 'Annie', 'Annie', 'Annie', 'Annie'],
        redTeamBans: ['Annie', 'Annie', 'Annie', 'Annie', 'Annie'],
        blueTeamPicks: ['Annie', 'Annie', 'Annie', 'Annie', 'Annie'],
        redTeamPicks: ['Annie', 'Annie', 'Annie', 'Annie', 'Annie'],
        blueTeamKills: 0,
        redTeamKills: 0,
        blueTeamDeath: 0,
        redTeamDeath: 0,
        blueTeamAsist: 0,
        redTeamAsist: 0,
        blueTeamGold: 8,
        redTeamGold: 8,
        duration: '35:20',
        blueTeam: [
          {
            name: '플레임',
            role: 'TOP',
            champion: 'Annie',
            kill: 0,
            death: 0,
            assist: 0,
            damage: 0,
            gold: 0,
          },
          {
            name: '소우릎',
            role: 'JG',
            champion: 'Annie',
            kill: 0,
            death: 0,
            assist: 0,
            damage: 0,
            gold: 0,
          },
          {
            name: '헤징',
            role: 'MID',
            champion: 'Annie',
            kill: 0,
            death: 0,
            assist: 0,
            damage: 0,
            gold: 0,
          },
          {
            name: '러너',
            role: 'ADC',
            champion: 'Annie',
            kill: 0,
            death: 0,
            assist: 0,
            damage: 0,
            gold: 0,
          },
          {
            name: '눈꽃',
            role: 'SUP',
            champion: 'Annie',
            kill: 0,
            death: 0,
            assist: 0,
            damage: 0,
            gold: 0,
          },
        ],
        redTeam: [
          {
            name: '룩삼',
            role: 'TOP',
            champion: 'Annie',
            kill: 0,
            death: 0,
            assist: 0,
            damage: 0,
            gold: 0,
          },
          {
            name: '앰비션',
            role: 'JG',
            champion: 'Annie',
            kill: 0,
            death: 0,
            assist: 0,
            damage: 0,
            gold: 0,
          },
          {
            name: '실프',
            role: 'MID',
            champion: 'Annie',
            kill: 0,
            death: 0,
            assist: 0,
            damage: 0,
            gold: 0,
          },
          {
            name: '따효니',
            role: 'ADC',
            champion: 'Annie',
            kill: 0,
            death: 0,
            assist: 0,
            damage: 0,
            gold: 0,
          },
          {
            name: '라콩',
            role: 'SUP',
            champion: 'Annie',
            kill: 0,
            death: 0,
            assist: 0,
            damage: 0,
            gold: 0,
          },
        ],
      },
      {
        id: 's1',
        setNumber: 3,
        winner: 'TEAM 큐베',
        blueTeamBans: ['Annie', 'Annie', 'Annie', 'Annie', 'Annie'],
        redTeamBans: ['Annie', 'Annie', 'Annie', 'Annie', 'Annie'],
        blueTeamPicks: ['Annie', 'Annie', 'Annie', 'Annie', 'Annie'],
        redTeamPicks: ['Annie', 'Annie', 'Annie', 'Annie', 'Annie'],
        blueTeamKills: 0,
        redTeamKills: 0,
        blueTeamDeath: 0,
        redTeamDeath: 0,
        blueTeamAsist: 0,
        redTeamAsist: 0,
        blueTeamGold: 8,
        redTeamGold: 8,
        duration: '35:20',
        blueTeam: [
          {
            name: '플레임',
            role: 'TOP',
            champion: 'Annie',
            kill: 0,
            death: 0,
            assist: 0,
            damage: 0,
            gold: 0,
          },
          {
            name: '소우릎',
            role: 'JG',
            champion: 'Annie',
            kill: 0,
            death: 0,
            assist: 0,
            damage: 0,
            gold: 0,
          },
          {
            name: '헤징',
            role: 'MID',
            champion: 'Annie',
            kill: 0,
            death: 0,
            assist: 0,
            damage: 0,
            gold: 0,
          },
          {
            name: '러너',
            role: 'ADC',
            champion: 'Annie',
            kill: 0,
            death: 0,
            assist: 0,
            damage: 0,
            gold: 0,
          },
          {
            name: '눈꽃',
            role: 'SUP',
            champion: 'Annie',
            kill: 0,
            death: 0,
            assist: 0,
            damage: 0,
            gold: 0,
          },
        ],
        redTeam: [
          {
            name: '룩삼',
            role: 'TOP',
            champion: 'Annie',
            kill: 0,
            death: 0,
            assist: 0,
            damage: 0,
            gold: 0,
          },
          {
            name: '앰비션',
            role: 'JG',
            champion: 'Annie',
            kill: 0,
            death: 0,
            assist: 0,
            damage: 0,
            gold: 0,
          },
          {
            name: '실프',
            role: 'MID',
            champion: 'Annie',
            kill: 0,
            death: 0,
            assist: 0,
            damage: 0,
            gold: 0,
          },
          {
            name: '따효니',
            role: 'ADC',
            champion: 'Annie',
            kill: 0,
            death: 0,
            assist: 0,
            damage: 0,
            gold: 0,
          },
          {
            name: '라콩',
            role: 'SUP',
            champion: 'Annie',
            kill: 0,
            death: 0,
            assist: 0,
            damage: 0,
            gold: 0,
          },
        ],
      },
    ],
  },
  {
    id: 'm2',
    matchNumber: 2,
    blueTeam: 'TEAM 앰비션',
    redTeam: 'TEAM 플레임',
    blueTeamScore: 0,
    redTeamScore: 0,
    date: '2025-04-06',
    completed: false,
    stage: '리그전',
    sets: [],
  },
  {
    id: 'm3',
    matchNumber: 3,
    blueTeam: 'TEAM 플레임',
    redTeam: 'TEAM 매드라이프',
    blueTeamScore: 0,
    redTeamScore: 0,
    date: '2025-04-07',
    completed: false,
    stage: '리그전',
    sets: [],
  },
  {
    id: 'm4',
    matchNumber: 4,
    blueTeam: 'TEAM 뱅',
    redTeam: 'TEAM 앰비션',
    blueTeamScore: 0,
    redTeamScore: 0,
    date: '2025-04-07',
    completed: false,
    stage: '리그전',
    sets: [],
  },
  {
    id: 'm5',
    matchNumber: 5,
    blueTeam: 'TEAM 매드라이프',
    redTeam: 'TEAM 앰비션',
    blueTeamScore: 0,
    redTeamScore: 0,
    date: '2025-04-08',
    completed: false,
    stage: '리그전',
    sets: [],
  },
  {
    id: 'm6',
    matchNumber: 6,
    blueTeam: 'TEAM 플레임',
    redTeam: 'TEAM 큐베',
    blueTeamScore: 0,
    redTeamScore: 0,
    date: '2025-04-08',
    completed: false,
    stage: '리그전',
    sets: [],
  },
  {
    id: 'm7',
    matchNumber: 7,
    blueTeam: 'TEAM 뱅',
    redTeam: 'TEAM 플레임',
    blueTeamScore: 0,
    redTeamScore: 0,
    date: '2025-04-09',
    completed: false,
    stage: '리그전',
    sets: [],
  },
  {
    id: 'm8',
    matchNumber: 8,
    blueTeam: 'TEAM 큐베',
    redTeam: 'TEAM 매드라이프',
    blueTeamScore: 0,
    redTeamScore: 0,
    date: '2025-04-09',
    completed: false,
    stage: '리그전',
    sets: [],
  },
  {
    id: 'm9',
    matchNumber: 9,
    blueTeam: 'TEAM 큐베',
    redTeam: 'TEAM 앰비션',
    blueTeamScore: 0,
    redTeamScore: 0,
    date: '2025-04-10',
    completed: false,
    stage: '리그전',
    sets: [],
  },
  {
    id: 'm10',
    matchNumber: 10,
    blueTeam: 'TEAM 뱅',
    redTeam: 'TEAM 매드라이프',
    blueTeamScore: 0,
    redTeamScore: 0,
    date: '2025-04-10',
    completed: false,
    stage: '리그전',
    sets: [],
  },
]

export default totalMatchData
