import { IMatch } from '@/types'

const totalMatchData: IMatch[] = [
  {
    id: 'm1',
    matchNumber: 1,
    blueTeam: 'TEAM 큐베',
    redTeam: 'TEAM 뱅',
    blueTeamScore: 0,
    redTeamScore: 0,
    date: '2025-04-06',
    completed: false,
    stage: '리그전',
    sets: [
      {
        id: 's1',
        setNumber: 1,
        winner: '',
        blueTeamBans: ['Varus', 'Ahri', 'Nautilus', 'Galio', 'Taliyah'],
        redTeamBans: ['Lulu', 'Draven', 'Sejuani', 'Orianna', 'Viktor'],
        blueTeamPicks: ['Vi', 'Caitlyn', 'Seraphine', 'Kassadin', 'Ambessa'],
        redTeamPicks: ['Naafiri', 'Ashe', 'Leona', 'Veigar', 'Darius'],
        blueTeamKills: 0,
        redTeamKills: 0,
        blueTeamDeath: 0,
        redTeamDeath: 0,
        blueTeamAsist: 0,
        redTeamAsist: 0,
        blueTeamGold: 8,
        redTeamGold: 8,
        duration: '',
        blueTeam: [
          {
            name: '강소연',
            champion: 'Ambessa',
            role: 'TOP',
            kill: 0,
            death: 0,
            assist: 0,
            damage: 0,
            gold: 0,
          },
          {
            name: '네클릿',
            champion: 'Vi',
            role: 'JG',
            kill: 0,
            death: 0,
            assist: 0,
            damage: 0,
            gold: 0,
          },
          {
            name: '큐베',
            champion: 'Kassadin',
            role: 'MID',
            kill: 0,
            death: 0,
            assist: 0,
            damage: 0,
            gold: 0,
          },
          {
            name: '크캣',
            champion: 'Caitlyn',
            role: 'ADC',
            kill: 0,
            death: 0,
            assist: 0,
            damage: 0,
            gold: 0,
          },
          {
            name: '루루카',
            champion: 'Seraphine',
            role: 'SUP',
            kill: 0,
            death: 0,
            assist: 0,
            damage: 0,
            gold: 0,
          },
        ],
        redTeam: [
          {
            name: '인섹',
            champion: 'Darius',
            role: 'TOP',
            kill: 0,
            death: 0,
            assist: 0,
            damage: 0,
            gold: 0,
          },
          {
            name: '고수달',
            champion: 'Naafiri',
            role: 'JG',
            kill: 0,
            death: 0,
            assist: 0,
            damage: 0,
            gold: 0,
          },
          {
            name: '인간젤리',
            champion: 'Veigar',
            role: 'MID',
            kill: 0,
            death: 0,
            assist: 0,
            damage: 0,
            gold: 0,
          },
          {
            name: '뱅',
            champion: 'Ashe',
            role: 'ADC',
            kill: 0,
            death: 0,
            assist: 0,
            damage: 0,
            gold: 0,
          },
          {
            name: '던',
            champion: 'Leona',
            role: 'SUP',
            kill: 0,
            death: 0,
            assist: 0,
            damage: 0,
            gold: 0,
          },
        ],
      },
    ],
  },
  {
    id: 'm2',
    matchNumber: 2,
    blueTeam: 'TEAM 앰비션',
    redTeam: 'TEAM 플레임',
    blueTeamScore: 0,
    redTeamScore: 0,
    date: '2025-04-06',
    completed: false,
    stage: '리그전',
    sets: [],
  },
  {
    id: 'm3',
    matchNumber: 3,
    blueTeam: 'TEAM 플레임',
    redTeam: 'TEAM 매드라이프',
    blueTeamScore: 0,
    redTeamScore: 0,
    date: '2025-04-07',
    completed: false,
    stage: '리그전',
    sets: [],
  },
  {
    id: 'm4',
    matchNumber: 4,
    blueTeam: 'TEAM 뱅',
    redTeam: 'TEAM 앰비션',
    blueTeamScore: 0,
    redTeamScore: 0,
    date: '2025-04-07',
    completed: false,
    stage: '리그전',
    sets: [],
  },
  {
    id: 'm5',
    matchNumber: 5,
    blueTeam: 'TEAM 매드라이프',
    redTeam: 'TEAM 앰비션',
    blueTeamScore: 0,
    redTeamScore: 0,
    date: '2025-04-08',
    completed: false,
    stage: '리그전',
    sets: [],
  },
  {
    id: 'm6',
    matchNumber: 6,
    blueTeam: 'TEAM 플레임',
    redTeam: 'TEAM 큐베',
    blueTeamScore: 0,
    redTeamScore: 0,
    date: '2025-04-08',
    completed: false,
    stage: '리그전',
    sets: [],
  },
  {
    id: 'm7',
    matchNumber: 7,
    blueTeam: 'TEAM 뱅',
    redTeam: 'TEAM 플레임',
    blueTeamScore: 0,
    redTeamScore: 0,
    date: '2025-04-09',
    completed: false,
    stage: '리그전',
    sets: [],
  },
  {
    id: 'm8',
    matchNumber: 8,
    blueTeam: 'TEAM 큐베',
    redTeam: 'TEAM 매드라이프',
    blueTeamScore: 0,
    redTeamScore: 0,
    date: '2025-04-09',
    completed: false,
    stage: '리그전',
    sets: [],
  },
  {
    id: 'm9',
    matchNumber: 9,
    blueTeam: 'TEAM 큐베',
    redTeam: 'TEAM 앰비션',
    blueTeamScore: 0,
    redTeamScore: 0,
    date: '2025-04-10',
    completed: false,
    stage: '리그전',
    sets: [],
  },
  {
    id: 'm10',
    matchNumber: 10,
    blueTeam: 'TEAM 뱅',
    redTeam: 'TEAM 매드라이프',
    blueTeamScore: 0,
    redTeamScore: 0,
    date: '2025-04-10',
    completed: false,
    stage: '리그전',
    sets: [],
  },
]

export default totalMatchData
