import { IMatch } from '@/types'

const totalMatchData: IMatch[] = [
  {
    id: 'm1',
    matchNumber: 1,
    blueTeam: 'TEAM 큐베',
    redTeam: 'TEAM 뱅',
    blueTeamScore: 1,
    redTeamScore: 0,
    date: '2025-04-06',
    completed: false,
    stage: '리그전',
    sets: [
      {
        id: 's1',
        setNumber: 1,
        winner: 'TEAM 큐베',
        blueTeamBans: ['Varus', 'Ahri', 'Nautilus', 'Galio', 'Taliyah'],
        redTeamBans: ['Lulu', 'Draven', 'Sejuani', 'Orianna', 'Viktor'],
        blueTeamPicks: ['Vi', 'Caitlyn', 'Seraphine', 'Kassadin', 'Ambessa'],
        redTeamPicks: ['Naafiri', 'Ashe', 'Leona', 'Veigar', 'Darius'],
        blueTeamKills: 44,
        redTeamKills: 16,
        blueTeamDeath: 16,
        redTeamDeath: 44,
        blueTeamAsist: 114,
        redTeamAsist: 42,
        blueTeamGold: 56949,
        redTeamGold: 46357,
        duration: '26:40',
        blueTeam: [
          {
            name: '강소연',
            champion: 'Ambessa',
            role: 'TOP',
            kill: 5,
            death: 5,
            assist: 16,
            damage: 13334,
            gold: 9553,
          },
          {
            name: '네클릿',
            champion: 'Vi',
            role: 'JG',
            kill: 7,
            death: 5,
            assist: 32,
            damage: 24792,
            gold: 12228,
          },
          {
            name: '큐베',
            champion: 'Kassadin',
            role: 'MID',
            kill: 20,
            death: 1,
            assist: 19,
            damage: 43000,
            gold: 14851,
          },
          {
            name: '크캣',
            champion: 'Caitlyn',
            role: 'ADC',
            kill: 8,
            death: 2,
            assist: 19,
            damage: 28287,
            gold: 12231,
          },
          {
            name: '루루카',
            champion: 'Seraphine',
            role: 'SUP',
            kill: 4,
            death: 3,
            assist: 28,
            damage: 6486,
            gold: 8086,
          },
        ],
        redTeam: [
          {
            name: '인섹',
            champion: 'Darius',
            role: 'TOP',
            kill: 8,
            death: 7,
            assist: 6,
            damage: 33391,
            gold: 13640,
          },
          {
            name: '고수달',
            champion: 'Naafiri',
            role: 'JG',
            kill: 2,
            death: 9,
            assist: 10,
            damage: 12293,
            gold: 9197,
          },
          {
            name: '인간젤리',
            champion: 'Veigar',
            role: 'MID',
            kill: 2,
            death: 10,
            assist: 10,
            damage: 17478,
            gold: 8414,
          },
          {
            name: '뱅',
            champion: 'Ashe',
            role: 'ADC',
            kill: 3,
            death: 9,
            assist: 8,
            damage: 11741,
            gold: 9202,
          },
          {
            name: '던',
            champion: 'Leona',
            role: 'SUP',
            kill: 1,
            death: 9,
            assist: 8,
            damage: 5513,
            gold: 5904,
          },
        ],
      },
    ],
  },
  {
    id: 'm2',
    matchNumber: 2,
    blueTeam: 'TEAM 앰비션',
    redTeam: 'TEAM 플레임',
    blueTeamScore: 0,
    redTeamScore: 0,
    date: '2025-04-06',
    completed: false,
    stage: '리그전',
    sets: [],
  },
  {
    id: 'm3',
    matchNumber: 3,
    blueTeam: 'TEAM 플레임',
    redTeam: 'TEAM 매드라이프',
    blueTeamScore: 0,
    redTeamScore: 0,
    date: '2025-04-07',
    completed: false,
    stage: '리그전',
    sets: [],
  },
  {
    id: 'm4',
    matchNumber: 4,
    blueTeam: 'TEAM 뱅',
    redTeam: 'TEAM 앰비션',
    blueTeamScore: 0,
    redTeamScore: 0,
    date: '2025-04-07',
    completed: false,
    stage: '리그전',
    sets: [],
  },
  {
    id: 'm5',
    matchNumber: 5,
    blueTeam: 'TEAM 매드라이프',
    redTeam: 'TEAM 앰비션',
    blueTeamScore: 0,
    redTeamScore: 0,
    date: '2025-04-08',
    completed: false,
    stage: '리그전',
    sets: [],
  },
  {
    id: 'm6',
    matchNumber: 6,
    blueTeam: 'TEAM 플레임',
    redTeam: 'TEAM 큐베',
    blueTeamScore: 0,
    redTeamScore: 0,
    date: '2025-04-08',
    completed: false,
    stage: '리그전',
    sets: [],
  },
  {
    id: 'm7',
    matchNumber: 7,
    blueTeam: 'TEAM 뱅',
    redTeam: 'TEAM 플레임',
    blueTeamScore: 0,
    redTeamScore: 0,
    date: '2025-04-09',
    completed: false,
    stage: '리그전',
    sets: [],
  },
  {
    id: 'm8',
    matchNumber: 8,
    blueTeam: 'TEAM 큐베',
    redTeam: 'TEAM 매드라이프',
    blueTeamScore: 0,
    redTeamScore: 0,
    date: '2025-04-09',
    completed: false,
    stage: '리그전',
    sets: [],
  },
  {
    id: 'm9',
    matchNumber: 9,
    blueTeam: 'TEAM 큐베',
    redTeam: 'TEAM 앰비션',
    blueTeamScore: 0,
    redTeamScore: 0,
    date: '2025-04-10',
    completed: false,
    stage: '리그전',
    sets: [],
  },
  {
    id: 'm10',
    matchNumber: 10,
    blueTeam: 'TEAM 뱅',
    redTeam: 'TEAM 매드라이프',
    blueTeamScore: 0,
    redTeamScore: 0,
    date: '2025-04-10',
    completed: false,
    stage: '리그전',
    sets: [],
  },
]

export default totalMatchData
