const dummy = {
  id: 'm1',
  matchNumber: 1,
  teamA: 'TEAM 큐베',
  teamB: 'TEAM 뱅',
  scoreA: 0,
  scoreB: 0,
  date: '2025-04-06',
  completed: false,
  sets: [
    {
      id: 's1',
      setNumber: 1,
      winner: '',
      blueTeamBans: [],
      redTeamBans: [],
      blueTeamPicks: [],
      redTeamPicks: [],
      blueTeamKills: 0,
      redTeamKills: 0,
      blueTeamDeath: 0,
      redTeamDeath: 0,
      blueTeamAsist: 0,
      redTeamAsist: 0,
      blueTeamGold: 8,
      redTeamGold: 8,
      duration: '',
      blueTeam: [
        {
          name: '',
          kill: 0,
          death: 0,
          assist: 0,
          damage: 0,
          gold: 0,
        },
        {
          name: '',
          kill: 0,
          death: 0,
          assist: 0,
          damage: 0,
          gold: 0,
        },
        {
          name: '',
          kill: 0,
          death: 0,
          assist: 0,
          damage: 0,
          gold: 0,
        },
        {
          name: '',
          kill: 0,
          death: 0,
          assist: 0,
          damage: 0,
          gold: 0,
        },
        {
          name: '',
          kill: 0,
          death: 0,
          assist: 0,
          damage: 0,
          gold: 0,
        },
      ],
      redTeam: [
        {
          name: '',
          kill: 0,
          death: 0,
          assist: 0,
          damage: 0,
          gold: 0,
        },
        {
          name: '',
          kill: 0,
          death: 0,
          assist: 0,
          damage: 0,
          gold: 0,
        },
        {
          name: '',
          kill: 0,
          death: 0,
          assist: 0,
          damage: 0,
          gold: 0,
        },
        {
          name: '',
          kill: 0,
          death: 0,
          assist: 0,
          damage: 0,
          gold: 0,
        },
        {
          name: '',
          kill: 0,
          death: 0,
          assist: 0,
          damage: 0,
          gold: 0,
        },
      ],
    },
  ],
}

export { dummy }
