import { IMatch } from '@/types'

const playoffMatchData: IMatch[] = [
  {
    id: 'm11',
    matchNumber: 11,
    blueTeam: '남성',
    redTeam: '상체파괴자',
    blueTeamScore: 1,
    redTeamScore: 0,
    date: '2025-04-12',
    completed: false,
    progress: true,
    stage: '플레이오프',
    sets: [
      {
        id: 's31',
        setNumber: 1,
        winner: '남성',
        blueTeamBans: ['Ambessa', 'Lucian', 'Gwen', 'Ashe', 'Nautilus'],
        redTeamBans: ['Hwei', 'Tristana', 'Vi', 'Rakan', 'Blitzcrank'],
        blueTeamPicks: ['Yone', 'Zyra', 'Sion', 'Jhin', 'Alistar'],
        redTeamPicks: ['Jayce', 'Lissandra', 'Nocturne', 'Varus', 'Leona'],
        blueTeamKills: 25,
        redTeamKills: 15,
        blueTeamDeath: 15,
        redTeamDeath: 25,
        blueTeamAsist: 60,
        redTeamAsist: 36,
        blueTeamGold: 60597,
        redTeamGold: 55047,
        duration: '31:12',
        blueTeam: [
          {
            name: '룩삼',
            champion: 'Sion',
            role: 'TOP',
            kill: 3,
            death: 0,
            assist: 16,
            damage: 16952,
            gold: 11119,
          },
          {
            name: '앰비션',
            champion: 'Zyra',
            role: 'JG',
            kill: 6,
            death: 3,
            assist: 14,
            damage: 33664,
            gold: 14156,
          },
          {
            name: '실프',
            champion: 'Yone',
            role: 'MID',
            kill: 8,
            death: 4,
            assist: 7,
            damage: 20346,
            gold: 13775,
          },
          {
            name: '따효니',
            champion: 'Jhin',
            role: 'ADC',
            kill: 5,
            death: 6,
            assist: 7,
            damage: 15834,
            gold: 12656,
          },
          {
            name: '라콩',
            champion: 'Alistar',
            role: 'SUP',
            kill: 3,
            death: 2,
            assist: 16,
            damage: 7863,
            gold: 8891,
          },
        ],
        redTeam: [
          {
            name: '플레임',
            champion: 'Jayce',
            role: 'TOP',
            kill: 1,
            death: 5,
            assist: 5,
            damage: 20250,
            gold: 11441,
          },
          {
            name: '소우릎',
            champion: 'Nocturne',
            role: 'JG',
            kill: 6,
            death: 5,
            assist: 7,
            damage: 17248,
            gold: 12392,
          },
          {
            name: '헤징',
            champion: 'Lissandra',
            role: 'MID',
            kill: 4,
            death: 4,
            assist: 5,
            damage: 23674,
            gold: 11850,
          },
          {
            name: '러너',
            champion: 'Varus',
            role: 'ADC',
            kill: 4,
            death: 6,
            assist: 7,
            damage: 15918,
            gold: 12017,
          },
          {
            name: '눈꽃',
            champion: 'Leona',
            role: 'SUP',
            kill: 0,
            death: 5,
            assist: 12,
            damage: 6798,
            gold: 7347,
          },
        ],
      },
    ],
  },
  {
    id: 'm12',
    matchNumber: 12,
    blueTeam: '노코멘트',
    redTeam: '돼굴단',
    blueTeamScore: 0,
    redTeamScore: 0,
    date: '2025-04-12',
    completed: false,
    progress: false,
    stage: '플레이오프',
    sets: [
      {
        id: '',
        setNumber: 1,
        winner: '',
        blueTeamBans: [],
        redTeamBans: [],
        blueTeamPicks: [],
        redTeamPicks: [],
        blueTeamKills: 0,
        redTeamKills: 0,
        blueTeamDeath: 0,
        redTeamDeath: 0,
        blueTeamAsist: 0,
        redTeamAsist: 0,
        blueTeamGold: 0,
        redTeamGold: 0,
        duration: '',
        blueTeam: [
          {
            name: '인섹',
            champion: '',
            role: 'TOP',
            kill: 0,
            death: 0,
            assist: 0,
            damage: 0,
            gold: 0,
          },
          {
            name: '고수달',
            champion: '',
            role: 'JG',
            kill: 0,
            death: 0,
            assist: 0,
            damage: 0,
            gold: 0,
          },
          {
            name: '인간젤리',
            champion: '',
            role: 'MID',
            kill: 0,
            death: 0,
            assist: 0,
            damage: 0,
            gold: 0,
          },
          {
            name: '뱅',
            champion: '',
            role: 'ADC',
            kill: 0,
            death: 0,
            assist: 0,
            damage: 0,
            gold: 0,
          },
          {
            name: '던',
            champion: '',
            role: 'SUP',
            kill: 0,
            death: 0,
            assist: 0,
            damage: 0,
            gold: 0,
          },
        ],
        redTeam: [
          {
            name: '강소연',
            champion: '',
            role: 'TOP',
            kill: 0,
            death: 0,
            assist: 0,
            damage: 0,
            gold: 0,
          },
          {
            name: '네클릿',
            champion: '',
            role: 'JG',
            kill: 0,
            death: 0,
            assist: 0,
            damage: 0,
            gold: 0,
          },
          {
            name: '큐베',
            champion: '',
            role: 'MID',
            kill: 0,
            death: 0,
            assist: 0,
            damage: 0,
            gold: 0,
          },
          {
            name: '크캣',
            champion: '',
            role: 'ADC',
            kill: 0,
            death: 0,
            assist: 0,
            damage: 0,
            gold: 0,
          },
          {
            name: '루루카',
            champion: '',
            role: 'SUP',
            kill: 0,
            death: 0,
            assist: 0,
            damage: 0,
            gold: 0,
          },
        ],
      },
    ],
  },
  {
    id: 'm13',
    matchNumber: 13,
    blueTeam: '1경기 승리팀',
    redTeam: '2경기 승리팀',
    blueTeamScore: 0,
    redTeamScore: 0,
    date: '2025-04-12',
    completed: false,
    progress: false,
    stage: '플레이오프',
    sets: [],
  },
  {
    id: 'm14',
    matchNumber: 14,
    blueTeam: '1경기 패배팀',
    redTeam: '2경기 패배팀',
    blueTeamScore: 0,
    redTeamScore: 0,
    date: '2025-04-12',
    completed: false,
    progress: false,
    stage: '플레이오프',
    sets: [],
  },
  {
    id: 'm15',
    matchNumber: 15,
    blueTeam: '승자조 배패팀',
    redTeam: '패자조 승리팀',
    blueTeamScore: 0,
    redTeamScore: 0,
    date: '2025-04-13',
    completed: false,
    progress: false,
    stage: '플레이오프',
    sets: [],
  },
  {
    id: 'm16',
    matchNumber: 16,
    blueTeam: '승자조 승리팀',
    redTeam: '최종 진출전 승리팀',
    blueTeamScore: 0,
    redTeamScore: 0,
    date: '2025-04-13',
    completed: false,
    progress: false,
    stage: '결승전',
    sets: [],
  },
]

export default playoffMatchData
