import { IMatch } from '@/types'

const playoffMatchData: IMatch[] = [
  {
    id: 'm11',
    matchNumber: 11,
    blueTeam: '남성',
    redTeam: '상체파괴자',
    blueTeamScore: 2,
    redTeamScore: 0,
    date: '2025-04-12',
    completed: true,
    progress: false,
    stage: '플레이오프',
    sets: [
      {
        id: 's31',
        setNumber: 1,
        winner: '남성',
        blueTeamBans: ['Ambessa', 'Lucian', 'Gwen', 'Ashe', 'Nautilus'],
        redTeamBans: ['Hwei', 'Tristana', 'Vi', 'Rakan', 'Blitzcrank'],
        blueTeamPicks: ['Yone', 'Zyra', 'Sion', 'Jhin', 'Alistar'],
        redTeamPicks: ['Jayce', 'Lissandra', 'Nocturne', 'Varus', 'Leona'],
        blueTeamKills: 25,
        redTeamKills: 15,
        blueTeamDeath: 15,
        redTeamDeath: 25,
        blueTeamAsist: 60,
        redTeamAsist: 36,
        blueTeamGold: 60597,
        redTeamGold: 55047,
        duration: '31:12',
        blueTeam: [
          {
            name: '룩삼',
            champion: 'Sion',
            role: 'TOP',
            kill: 3,
            death: 0,
            assist: 16,
            damage: 16952,
            gold: 11119,
          },
          {
            name: '앰비션',
            champion: 'Zyra',
            role: 'JG',
            kill: 6,
            death: 3,
            assist: 14,
            damage: 33664,
            gold: 14156,
          },
          {
            name: '실프',
            champion: 'Yone',
            role: 'MID',
            kill: 8,
            death: 4,
            assist: 7,
            damage: 20346,
            gold: 13775,
          },
          {
            name: '따효니',
            champion: 'Jhin',
            role: 'ADC',
            kill: 5,
            death: 6,
            assist: 7,
            damage: 15834,
            gold: 12656,
          },
          {
            name: '라콩',
            champion: 'Alistar',
            role: 'SUP',
            kill: 3,
            death: 2,
            assist: 16,
            damage: 7863,
            gold: 8891,
          },
        ],
        redTeam: [
          {
            name: '플레임',
            champion: 'Jayce',
            role: 'TOP',
            kill: 1,
            death: 5,
            assist: 5,
            damage: 20250,
            gold: 11441,
          },
          {
            name: '소우릎',
            champion: 'Nocturne',
            role: 'JG',
            kill: 6,
            death: 5,
            assist: 7,
            damage: 17248,
            gold: 12392,
          },
          {
            name: '헤징',
            champion: 'Lissandra',
            role: 'MID',
            kill: 4,
            death: 4,
            assist: 5,
            damage: 23674,
            gold: 11850,
          },
          {
            name: '러너',
            champion: 'Varus',
            role: 'ADC',
            kill: 4,
            death: 6,
            assist: 7,
            damage: 15918,
            gold: 12017,
          },
          {
            name: '눈꽃',
            champion: 'Leona',
            role: 'SUP',
            kill: 0,
            death: 5,
            assist: 12,
            damage: 6798,
            gold: 7347,
          },
        ],
      },
      {
        id: 's32',
        setNumber: 2,
        winner: '남성',
        blueTeamBans: ['Ambessa', 'Gwen', 'Vi', 'Naafiri', 'MonkeyKing'],
        redTeamBans: ['Hwei', 'Tristana', 'Sylas', 'Garen', 'Caitlyn'],
        blueTeamPicks: [
          'XinZhao',
          'Nautilus',
          'Orianna',
          'MissFortune',
          'Mordekaiser',
        ],
        redTeamPicks: ['Viktor', 'Lucian', 'Braum', 'Poppy', 'DrMundo'],
        blueTeamKills: 23,
        redTeamKills: 5,
        blueTeamDeath: 5,
        redTeamDeath: 23,
        blueTeamAsist: 48,
        redTeamAsist: 9,
        blueTeamGold: 61045,
        redTeamGold: 47021,
        duration: '30:48',
        blueTeam: [
          {
            name: '룩삼',
            champion: 'Mordekaiser',
            role: 'TOP',
            kill: 3,
            death: 0,
            assist: 4,
            damage: 18418,
            gold: 11547,
          },
          {
            name: '앰비션',
            champion: 'XinZhao',
            role: 'JG',
            kill: 4,
            death: 1,
            assist: 11,
            damage: 25167,
            gold: 12326,
          },
          {
            name: '실프',
            champion: 'Orianna',
            role: 'MID',
            kill: 5,
            death: 1,
            assist: 10,
            damage: 22567,
            gold: 13098,
          },
          {
            name: '따효니',
            champion: 'MissFortune',
            role: 'ADC',
            kill: 9,
            death: 1,
            assist: 10,
            damage: 31466,
            gold: 15187,
          },
          {
            name: '라콩',
            champion: 'Nautilus',
            role: 'SUP',
            kill: 2,
            death: 2,
            assist: 13,
            damage: 7677,
            gold: 8887,
          },
        ],
        redTeam: [
          {
            name: '플레임',
            champion: 'DrMundo',
            role: 'TOP',
            kill: 1,
            death: 3,
            assist: 0,
            damage: 19995,
            gold: 11347,
          },
          {
            name: '소우릎',
            champion: 'Poppy',
            role: 'JG',
            kill: 0,
            death: 5,
            assist: 2,
            damage: 8559,
            gold: 8622,
          },
          {
            name: '헤징',
            champion: 'Viktor',
            role: 'MID',
            kill: 0,
            death: 3,
            assist: 2,
            damage: 19642,
            gold: 8950,
          },
          {
            name: '러너',
            champion: 'Lucian',
            role: 'ADC',
            kill: 3,
            death: 7,
            assist: 2,
            damage: 12350,
            gold: 10930,
          },
          {
            name: '눈꽃',
            champion: 'Braum',
            role: 'SUP',
            kill: 1,
            death: 5,
            assist: 3,
            damage: 7259,
            gold: 7172,
          },
        ],
      },
    ],
  },
  {
    id: 'm12',
    matchNumber: 12,
    blueTeam: '노코멘트',
    redTeam: '돼굴단',
    blueTeamScore: 1,
    redTeamScore: 2,
    date: '2025-04-12',
    completed: true,
    progress: false,
    stage: '플레이오프',
    sets: [
      {
        id: 's33',
        setNumber: 1,
        winner: '노코멘트',
        blueTeamBans: ['Draven', 'Lulu', 'Vi', 'Seraphine', 'Milio'],
        redTeamBans: ['Varus', 'Gwen', 'Xayah', 'Zeri', 'Lucian'],
        blueTeamPicks: ['Yone', 'Sejuani', 'Yuumi', 'Ezreal', 'Ryze'],
        redTeamPicks: ['Ahri', 'Nocturne', 'Malphite', 'Caitlyn', 'Soraka'],
        blueTeamKills: 17,
        redTeamKills: 9,
        blueTeamDeath: 9,
        redTeamDeath: 17,
        blueTeamAsist: 45,
        redTeamAsist: 23,
        blueTeamGold: 65371,
        redTeamGold: 55707,
        duration: '34:27',
        blueTeam: [
          {
            name: '인섹',
            champion: 'Yone',
            role: 'TOP',
            kill: 3,
            death: 3,
            assist: 6,
            damage: 24578,
            gold: 14096,
          },
          {
            name: '고수달',
            champion: 'Sejuani',
            role: 'JG',
            kill: 4,
            death: 2,
            assist: 7,
            damage: 12636,
            gold: 12545,
          },
          {
            name: '인간젤리',
            champion: 'Ryze',
            role: 'MID',
            kill: 5,
            death: 3,
            assist: 6,
            damage: 23982,
            gold: 15599,
          },
          {
            name: '뱅',
            champion: 'Ezreal',
            role: 'ADC',
            kill: 4,
            death: 1,
            assist: 11,
            damage: 39684,
            gold: 14164,
          },
          {
            name: '던',
            champion: 'Yuumi',
            role: 'SUP',
            kill: 1,
            death: 0,
            assist: 15,
            damage: 9064,
            gold: 8967,
          },
        ],
        redTeam: [
          {
            name: '강소연',
            champion: 'Malphite',
            role: 'TOP',
            kill: 3,
            death: 3,
            assist: 3,
            damage: 15760,
            gold: 11363,
          },
          {
            name: '네클릿',
            champion: 'Nocturne',
            role: 'JG',
            kill: 2,
            death: 2,
            assist: 4,
            damage: 10175,
            gold: 12105,
          },
          {
            name: '큐베',
            champion: 'Ahri',
            role: 'MID',
            kill: 2,
            death: 2,
            assist: 4,
            damage: 23285,
            gold: 13004,
          },
          {
            name: '크캣',
            champion: 'Caitlyn',
            role: 'ADC',
            kill: 2,
            death: 5,
            assist: 5,
            damage: 18434,
            gold: 12199,
          },
          {
            name: '루루카',
            champion: 'Soraka',
            role: 'SUP',
            kill: 0,
            death: 5,
            assist: 7,
            damage: 3030,
            gold: 7036,
          },
        ],
      },
      {
        id: 's34',
        setNumber: 2,
        winner: '돼굴단',
        blueTeamBans: ['Draven', 'Lulu', 'Sion', 'Viktor', 'Orianna'],
        redTeamBans: ['Varus', 'Gwen', 'Ambessa', 'Nautilus', 'Maokai'],
        blueTeamPicks: ['XinZhao', 'Kalista', 'Olaf', 'Leona', 'Malzahar'],
        redTeamPicks: ['Vi', 'Ashe', 'Seraphine', 'Yorick', 'Vladimir'],
        blueTeamKills: 13,
        redTeamKills: 30,
        blueTeamDeath: 30,
        redTeamDeath: 13,
        blueTeamAsist: 22,
        redTeamAsist: 66,
        blueTeamGold: 55040,
        redTeamGold: 65356,
        duration: '32:02',
        blueTeam: [
          {
            name: '인섹',
            champion: 'Olaf',
            role: 'TOP',
            kill: 5,
            death: 6,
            assist: 2,
            damage: 22293,
            gold: 13215,
          },
          {
            name: '고수달',
            champion: 'XinZhao',
            role: 'JG',
            kill: 1,
            death: 7,
            assist: 7,
            damage: 7327,
            gold: 10789,
          },
          {
            name: '인간젤리',
            champion: 'Malzahar',
            role: 'MID',
            kill: 1,
            death: 6,
            assist: 4,
            damage: 25099,
            gold: 10779,
          },
          {
            name: '뱅',
            champion: 'Kalista',
            role: 'ADC',
            kill: 5,
            death: 5,
            assist: 2,
            damage: 15147,
            gold: 13201,
          },
          {
            name: '던',
            champion: 'Leona',
            role: 'SUP',
            kill: 1,
            death: 6,
            assist: 7,
            damage: 5439,
            gold: 7056,
          },
        ],
        redTeam: [
          {
            name: '강소연',
            champion: 'Yorick',
            role: 'TOP',
            kill: 4,
            death: 3,
            assist: 8,
            damage: 15721,
            gold: 12259,
          },
          {
            name: '네클릿',
            champion: 'Vi',
            role: 'JG',
            kill: 8,
            death: 3,
            assist: 11,
            damage: 21350,
            gold: 14071,
          },
          {
            name: '큐베',
            champion: 'Vladimir',
            role: 'MID',
            kill: 13,
            death: 4,
            assist: 10,
            damage: 41826,
            gold: 16234,
          },
          {
            name: '크캣',
            champion: 'Ashe',
            role: 'ADC',
            kill: 5,
            death: 3,
            assist: 12,
            damage: 21343,
            gold: 13254,
          },
          {
            name: '루루카',
            champion: 'Seraphine',
            role: 'SUP',
            kill: 0,
            death: 0,
            assist: 25,
            damage: 5558,
            gold: 9538,
          },
        ],
      },
      {
        id: 's35',
        setNumber: 3,
        winner: '돼굴단',
        blueTeamBans: ['Draven', 'Lulu', 'Orianna', 'Mordekaiser', 'Nasus'],
        redTeamBans: ['Varus', 'Gwen', 'Ambessa', 'Darius', 'Aatrox'],
        blueTeamPicks: [
          'Viktor',
          'MonkeyKing',
          'Nautilus',
          'MissFortune',
          'AurelionSol',
        ],
        redTeamPicks: ['Milio', 'Tristana', 'Zyra', 'Sion', 'Jinx'],
        blueTeamKills: 4,
        redTeamKills: 17,
        blueTeamDeath: 17,
        redTeamDeath: 4,
        blueTeamAsist: 10,
        redTeamAsist: 35,
        blueTeamGold: 44212,
        redTeamGold: 54822,
        duration: '27:59',
        blueTeam: [
          {
            name: '인섹',
            champion: 'Viktor',
            role: 'TOP',
            kill: 1,
            death: 4,
            assist: 2,
            damage: 22172,
            gold: 9368,
          },
          {
            name: '고수달',
            champion: 'MonkeyKing',
            role: 'JG',
            kill: 1,
            death: 5,
            assist: 3,
            damage: 6030,
            gold: 8538,
          },
          {
            name: '인간젤리',
            champion: 'AurelionSol',
            role: 'MID',
            kill: 0,
            death: 2,
            assist: 1,
            damage: 10177,
            gold: 8294,
          },
          {
            name: '뱅',
            champion: 'MissFortune',
            role: 'ADC',
            kill: 2,
            death: 0,
            assist: 1,
            damage: 16321,
            gold: 12263,
          },
          {
            name: '던',
            champion: 'Nautilus',
            role: 'SUP',
            kill: 0,
            death: 6,
            assist: 3,
            damage: 3538,
            gold: 5749,
          },
        ],
        redTeam: [
          {
            name: '강소연',
            champion: 'Sion',
            role: 'TOP',
            kill: 1,
            death: 1,
            assist: 7,
            damage: 9253,
            gold: 9600,
          },
          {
            name: '네클릿',
            champion: 'Zyra',
            role: 'JG',
            kill: 2,
            death: 1,
            assist: 9,
            damage: 19942,
            gold: 11664,
          },
          {
            name: '큐베',
            champion: 'Tristana',
            role: 'MID',
            kill: 9,
            death: 1,
            assist: 3,
            damage: 37958,
            gold: 15053,
          },
          {
            name: '크캣',
            champion: 'Jinx',
            role: 'ADC',
            kill: 5,
            death: 1,
            assist: 5,
            damage: 15749,
            gold: 11505,
          },
          {
            name: '루루카',
            champion: 'Milio',
            role: 'SUP',
            kill: 0,
            death: 0,
            assist: 11,
            damage: 2013,
            gold: 7000,
          },
        ],
      },
    ],
  },
  {
    id: 'm13',
    matchNumber: 13,
    blueTeam: '남성',
    redTeam: '돼굴단',
    blueTeamScore: 2,
    redTeamScore: 0,
    date: '2025-04-12',
    completed: true,
    progress: false,
    stage: '플레이오프',
    sets: [
      {
        id: 's36',
        setNumber: 1,
        winner: '남성',
        blueTeamBans: ['Draven', 'Caitlyn', 'Yuumi', 'Jinx', 'Illaoi'],
        redTeamBans: ['Gwen', 'Lillia', 'Zyra', 'Nautilus', 'Blitzcrank'],
        blueTeamPicks: ['Vi', 'Sion', 'Tristana', 'Hwei', 'Rakan'],
        redTeamPicks: ['Yone', 'Sejuani', 'Lulu', 'Corki', 'Ambessa'],
        blueTeamKills: 20,
        redTeamKills: 13,
        blueTeamDeath: 13,
        redTeamDeath: 20,
        blueTeamAsist: 36,
        redTeamAsist: 26,
        blueTeamGold: 53428,
        redTeamGold: 47324,
        duration: '28:01',
        blueTeam: [
          {
            name: '룩삼',
            champion: 'Sion',
            role: 'TOP',
            kill: 2,
            death: 0,
            assist: 10,
            damage: 15130,
            gold: 10722,
          },
          {
            name: '앰비션',
            champion: 'Vi',
            role: 'JG',
            kill: 9,
            death: 3,
            assist: 8,
            damage: 24354,
            gold: 12900,
          },
          {
            name: '실프',
            champion: 'Hwei',
            role: 'MID',
            kill: 3,
            death: 2,
            assist: 8,
            damage: 21472,
            gold: 10584,
          },
          {
            name: '따효니',
            champion: 'Tristana',
            role: 'ADC',
            kill: 5,
            death: 4,
            assist: 2,
            damage: 10155,
            gold: 12343,
          },
          {
            name: '라콩',
            champion: 'Rakan',
            role: 'SUP',
            kill: 1,
            death: 4,
            assist: 8,
            damage: 2833,
            gold: 6879,
          },
        ],
        redTeam: [
          {
            name: '강소연',
            champion: 'Ambessa',
            role: 'TOP',
            kill: 2,
            death: 4,
            assist: 3,
            damage: 15018,
            gold: 9496,
          },
          {
            name: '네클릿',
            champion: 'Sejuani',
            role: 'JG',
            kill: 3,
            death: 5,
            assist: 7,
            damage: 10767,
            gold: 9510,
          },
          {
            name: '큐베',
            champion: 'Yone',
            role: 'MID',
            kill: 5,
            death: 5,
            assist: 3,
            damage: 16957,
            gold: 11025,
          },
          {
            name: '크캣',
            champion: 'Corki',
            role: 'ADC',
            kill: 3,
            death: 2,
            assist: 3,
            damage: 17970,
            gold: 10870,
          },
          {
            name: '루루카',
            champion: 'Lulu',
            role: 'SUP',
            kill: 0,
            death: 4,
            assist: 10,
            damage: 5824,
            gold: 6423,
          },
        ],
      },
      {
        id: 's37',
        setNumber: 2,
        winner: '남성',
        blueTeamBans: ['Draven', 'Caitlyn', 'Yuumi', 'Orianna', 'Ahri'],
        redTeamBans: ['Gwen', 'Lillia', 'XinZhao', 'Garen', 'Viego'],
        blueTeamPicks: ['Viktor', 'Jhin', 'Blitzcrank', 'MonkeyKing', 'Singed'],
        redTeamPicks: ['Nocturne', 'Jinx', 'Milio', 'Vladimir', 'Olaf'],
        blueTeamKills: 23,
        redTeamKills: 4,
        blueTeamDeath: 4,
        redTeamDeath: 23,
        blueTeamAsist: 49,
        redTeamAsist: 9,
        blueTeamGold: 56207,
        redTeamGold: 42628,
        duration: '26:42',
        blueTeam: [
          {
            name: '룩삼',
            champion: 'Singed',
            role: 'TOP',
            kill: 4,
            death: 1,
            assist: 6,
            damage: 15753,
            gold: 12795,
          },
          {
            name: '앰비션',
            champion: 'MonkeyKing',
            role: 'JG',
            kill: 8,
            death: 1,
            assist: 10,
            damage: 17422,
            gold: 12241,
          },
          {
            name: '실프',
            champion: 'Viktor',
            role: 'MID',
            kill: 8,
            death: 0,
            assist: 8,
            damage: 33763,
            gold: 13055,
          },
          {
            name: '따효니',
            champion: 'Jhin',
            role: 'ADC',
            kill: 1,
            death: 1,
            assist: 11,
            damage: 12311,
            gold: 10445,
          },
          {
            name: '라콩',
            champion: 'Blitzcrank',
            role: 'SUP',
            kill: 2,
            death: 1,
            assist: 14,
            damage: 6373,
            gold: 7641,
          },
        ],
        redTeam: [
          {
            name: '강소연',
            champion: 'Olaf',
            role: 'TOP',
            kill: 3,
            death: 3,
            assist: 1,
            damage: 11568,
            gold: 10381,
          },
          {
            name: '네클릿',
            champion: 'Nocturne',
            role: 'JG',
            kill: 0,
            death: 6,
            assist: 4,
            damage: 8877,
            gold: 8446,
          },
          {
            name: '큐베',
            champion: 'Vladimir',
            role: 'MID',
            kill: 1,
            death: 5,
            assist: 0,
            damage: 15850,
            gold: 9570,
          },
          {
            name: '크캣',
            champion: 'Jinx',
            role: 'ADC',
            kill: 0,
            death: 6,
            assist: 2,
            damage: 14275,
            gold: 8823,
          },
          {
            name: '루루카',
            champion: 'Milio',
            role: 'SUP',
            kill: 0,
            death: 3,
            assist: 2,
            damage: 3476,
            gold: 5408,
          },
        ],
      },
    ],
  },
  {
    id: 'm14',
    matchNumber: 14,
    blueTeam: '상체파괴자',
    redTeam: '노코멘트',
    blueTeamScore: 1,
    redTeamScore: 2,
    date: '2025-04-12',
    completed: true,
    progress: false,
    stage: '플레이오프',
    sets: [
      {
        id: 's38',
        setNumber: 1,
        winner: '노코멘트',
        blueTeamBans: ['Ezreal', 'Xayah', 'Ahri', 'Tristana', 'Sivir'],
        redTeamBans: ['Lissandra', 'Naafiri', 'Gwen', 'Rakan', 'Nautilus'],
        blueTeamPicks: ['Nocturne', 'Lucian', 'Kennen', 'Orianna', 'Galio'],
        redTeamPicks: ['Ambessa', 'Lillia', 'Yuumi', 'Corki', 'Taliyah'],
        blueTeamKills: 8,
        redTeamKills: 15,
        blueTeamDeath: 15,
        redTeamDeath: 8,
        blueTeamAsist: 16,
        redTeamAsist: 35,
        blueTeamGold: 49254,
        redTeamGold: 56313,
        duration: '30:30',
        blueTeam: [
          {
            name: '플레임',
            champion: 'Kennen',
            role: 'TOP',
            kill: 1,
            death: 1,
            assist: 0,
            damage: 13718,
            gold: 11124,
          },
          {
            name: '소우릎',
            champion: 'Nocturne',
            role: 'JG',
            kill: 1,
            death: 2,
            assist: 6,
            damage: 10091,
            gold: 9785,
          },
          {
            name: '헤징',
            champion: 'Orianna',
            role: 'MID',
            kill: 4,
            death: 4,
            assist: 1,
            damage: 12224,
            gold: 11287,
          },
          {
            name: '러너',
            champion: 'Lucian',
            role: 'ADC',
            kill: 2,
            death: 4,
            assist: 4,
            damage: 8681,
            gold: 10690,
          },
          {
            name: '눈꽃',
            champion: 'Galio',
            role: 'SUP',
            kill: 0,
            death: 4,
            assist: 5,
            damage: 3524,
            gold: 6368,
          },
        ],
        redTeam: [
          {
            name: '인섹',
            champion: 'Ambessa',
            role: 'TOP',
            kill: 2,
            death: 1,
            assist: 4,
            damage: 13743,
            gold: 11953,
          },
          {
            name: '고수달',
            champion: 'Lillia',
            role: 'JG',
            kill: 4,
            death: 1,
            assist: 4,
            damage: 14197,
            gold: 11853,
          },
          {
            name: '인간젤리',
            champion: 'Taliyah',
            role: 'MID',
            kill: 1,
            death: 1,
            assist: 7,
            damage: 11725,
            gold: 10618,
          },
          {
            name: '뱅',
            champion: 'Corki',
            role: 'ADC',
            kill: 6,
            death: 4,
            assist: 7,
            damage: 29540,
            gold: 13929,
          },
          {
            name: '던',
            champion: 'Yuumi',
            role: 'SUP',
            kill: 2,
            death: 1,
            assist: 13,
            damage: 4477,
            gold: 7960,
          },
        ],
      },
      {
        id: 's39',
        setNumber: 2,
        winner: '상체파괴자',
        blueTeamBans: ['Ezreal', 'Xayah', 'Ahri', 'Sivir', 'MissFortune'],
        redTeamBans: ['Naafiri', 'Yone', 'Gwen', 'Rakan', 'Nautilus'],
        blueTeamPicks: ['Vi', 'Jayce', 'Neeko', 'Ashe', 'Alistar'],
        redTeamPicks: ['Viego', 'Lissandra', 'Gragas', 'Braum', 'Smolder'],
        blueTeamKills: 23,
        redTeamKills: 9,
        blueTeamDeath: 9,
        redTeamDeath: 23,
        blueTeamAsist: 64,
        redTeamAsist: 26,
        blueTeamGold: 54164,
        redTeamGold: 44850,
        duration: '28:56',
        blueTeam: [
          {
            name: '플레임',
            champion: 'Jayce',
            role: 'TOP',
            kill: 8,
            death: 1,
            assist: 11,
            damage: 29346,
            gold: 14098,
          },
          {
            name: '소우릎',
            champion: 'Vi',
            role: 'JG',
            kill: 0,
            death: 3,
            assist: 10,
            damage: 9283,
            gold: 8905,
          },
          {
            name: '헤징',
            champion: 'Neeko',
            role: 'MID',
            kill: 4,
            death: 1,
            assist: 15,
            damage: 22352,
            gold: 10848,
          },
          {
            name: '러너',
            champion: 'Ashe',
            role: 'ADC',
            kill: 8,
            death: 1,
            assist: 11,
            damage: 29379,
            gold: 12395,
          },
          {
            name: '눈꽃',
            champion: 'Alistar',
            role: 'SUP',
            kill: 3,
            death: 3,
            assist: 17,
            damage: 6203,
            gold: 7918,
          },
        ],
        redTeam: [
          {
            name: '인섹',
            champion: 'Gragas',
            role: 'TOP',
            kill: 2,
            death: 3,
            assist: 3,
            damage: 13502,
            gold: 9787,
          },
          {
            name: '고수달',
            champion: 'Viego',
            role: 'JG',
            kill: 3,
            death: 5,
            assist: 5,
            damage: 7576,
            gold: 9242,
          },
          {
            name: '인간젤리',
            champion: 'Lissandra',
            role: 'MID',
            kill: 1,
            death: 4,
            assist: 5,
            damage: 13598,
            gold: 8916,
          },
          {
            name: '뱅',
            champion: 'Smolder',
            role: 'ADC',
            kill: 2,
            death: 5,
            assist: 6,
            damage: 26315,
            gold: 10612,
          },
          {
            name: '던',
            champion: 'Braum',
            role: 'SUP',
            kill: 1,
            death: 6,
            assist: 7,
            damage: 3663,
            gold: 6293,
          },
        ],
      },
      {
        id: 's40',
        setNumber: 3,
        winner: '노코멘트',
        blueTeamBans: ['Ezreal', 'Xayah', 'Ahri', 'MissFortune', 'Sylas'],
        redTeamBans: ['Naafiri', 'Yone', 'Gwen', 'Aatrox', 'Gnar'],
        blueTeamPicks: ['Leona', 'Aurora', 'MonkeyKing', 'Sivir', 'Swain'],
        redTeamPicks: ['Ryze', 'Maokai', 'DrMundo', 'Tristana', 'Veigar'],
        blueTeamKills: 7,
        redTeamKills: 19,
        blueTeamDeath: 19,
        redTeamDeath: 7,
        blueTeamAsist: 20,
        redTeamAsist: 42,
        blueTeamGold: 44355,
        redTeamGold: 58430,
        duration: '28:54',
        blueTeam: [
          {
            name: '플레임',
            champion: 'Aurora',
            role: 'TOP',
            kill: 1,
            death: 5,
            assist: 4,
            damage: 19126,
            gold: 9314,
          },
          {
            name: '소우릎',
            champion: 'MonkeyKing',
            role: 'JG',
            kill: 1,
            death: 2,
            assist: 4,
            damage: 12241,
            gold: 8983,
          },
          {
            name: '헤징',
            champion: 'Swain',
            role: 'MID',
            kill: 3,
            death: 3,
            assist: 3,
            damage: 14629,
            gold: 10455,
          },
          {
            name: '러너',
            champion: 'Sivir',
            role: 'ADC',
            kill: 2,
            death: 4,
            assist: 4,
            damage: 18496,
            gold: 9910,
          },
          {
            name: '눈꽃',
            champion: 'Leona',
            role: 'SUP',
            kill: 0,
            death: 5,
            assist: 5,
            damage: 3255,
            gold: 5673,
          },
        ],
        redTeam: [
          {
            name: '인섹',
            champion: 'Ryze',
            role: 'TOP',
            kill: 2,
            death: 2,
            assist: 11,
            damage: 19871,
            gold: 12507,
          },
          {
            name: '고수달',
            champion: 'DrMundo',
            role: 'JG',
            kill: 3,
            death: 0,
            assist: 12,
            damage: 19687,
            gold: 11596,
          },
          {
            name: '인간젤리',
            champion: 'Veigar',
            role: 'MID',
            kill: 5,
            death: 2,
            assist: 5,
            damage: 16008,
            gold: 11743,
          },
          {
            name: '뱅',
            champion: 'Tristana',
            role: 'ADC',
            kill: 9,
            death: 0,
            assist: 3,
            damage: 26541,
            gold: 14878,
          },
          {
            name: '던',
            champion: 'Maokai',
            role: 'SUP',
            kill: 0,
            death: 3,
            assist: 11,
            damage: 6147,
            gold: 7706,
          },
        ],
      },
    ],
  },
  {
    id: 'm15',
    matchNumber: 15,
    blueTeam: '노코멘트',
    redTeam: '돼굴단',
    blueTeamScore: 2,
    redTeamScore: 1,
    date: '2025-04-13',
    completed: true,
    progress: false,
    stage: '플레이오프',
    sets: [
      {
        id: 's41',
        setNumber: 1,
        winner: '노코멘트',
        blueTeamBans: ['Draven', 'Vi', 'Lulu', 'DrMundo', 'Sion'],
        redTeamBans: ['Gwen', 'Varus', 'Ezreal', 'Kaisa', 'Kalista'],
        blueTeamPicks: ['Ambessa', 'Sejuani', 'Nautilus', 'Taliyah', 'Smolder'],
        redTeamPicks: ['Yuumi', 'Yone', 'Zeri', 'Zyra', 'Mordekaiser'],
        blueTeamKills: 19,
        redTeamKills: 11,
        blueTeamDeath: 11,
        redTeamDeath: 19,
        blueTeamAsist: 43,
        redTeamAsist: 20,
        blueTeamGold: 68290,
        redTeamGold: 55818,
        duration: '35:02',
        blueTeam: [
          {
            name: '인섹',
            champion: 'Ambessa',
            role: 'TOP',
            kill: 9,
            death: 3,
            assist: 5,
            damage: 30448,
            gold: 16664,
          },
          {
            name: '고수달',
            champion: 'Sejuani',
            role: 'JG',
            kill: 2,
            death: 1,
            assist: 12,
            damage: 12352,
            gold: 12603,
          },
          {
            name: '인간젤리',
            champion: 'Taliyah',
            role: 'MID',
            kill: 4,
            death: 3,
            assist: 6,
            damage: 21323,
            gold: 14280,
          },
          {
            name: '뱅',
            champion: 'Smolder',
            role: 'ADC',
            kill: 3,
            death: 1,
            assist: 7,
            damage: 26100,
            gold: 16337,
          },
          {
            name: '던',
            champion: 'Nautilus',
            role: 'SUP',
            kill: 1,
            death: 4,
            assist: 13,
            damage: 4161,
            gold: 8406,
          },
        ],
        redTeam: [
          {
            name: '강소연',
            champion: 'Mordekaiser',
            role: 'TOP',
            kill: 0,
            death: 8,
            assist: 5,
            damage: 8059,
            gold: 8965,
          },
          {
            name: '네클릿',
            champion: 'Zyra',
            role: 'JG',
            kill: 2,
            death: 2,
            assist: 6,
            damage: 21971,
            gold: 11633,
          },
          {
            name: '큐베',
            champion: 'Yone',
            role: 'MID',
            kill: 3,
            death: 5,
            assist: 3,
            damage: 20643,
            gold: 12959,
          },
          {
            name: '크캣',
            champion: 'Zeri',
            role: 'ADC',
            kill: 6,
            death: 2,
            assist: 0,
            damage: 23353,
            gold: 15375,
          },
          {
            name: '루루카',
            champion: 'Yuumi',
            role: 'SUP',
            kill: 0,
            death: 2,
            assist: 6,
            damage: 7174,
            gold: 6885,
          },
        ],
      },
      {
        id: 's42',
        setNumber: 2,
        winner: '돼굴단',
        blueTeamBans: ['Draven', 'Vi', 'Lulu', 'Sion', 'Nasus'],
        redTeamBans: ['Gwen', 'Varus', 'Tristana', 'Kaisa', 'MissFortune'],
        blueTeamPicks: ['Ryze', 'Maokai', 'DrMundo', 'Olaf', 'Ezreal'],
        redTeamPicks: ['XinZhao', 'Caitlyn', 'Milio', 'Viktor', 'Garen'],
        blueTeamKills: 16,
        redTeamKills: 24,
        blueTeamDeath: 24,
        redTeamDeath: 16,
        blueTeamAsist: 43,
        redTeamAsist: 66,
        blueTeamGold: 64812,
        redTeamGold: 71857,
        duration: '39:31',
        blueTeam: [
          {
            name: '인섹',
            champion: 'Olaf',
            role: 'TOP',
            kill: 4,
            death: 5,
            assist: 5,
            damage: 30166,
            gold: 13869,
          },
          {
            name: '고수달',
            champion: 'DrMundo',
            role: 'JG',
            kill: 1,
            death: 5,
            assist: 11,
            damage: 29332,
            gold: 12221,
          },
          {
            name: '인간젤리',
            champion: 'Ryze',
            role: 'MID',
            kill: 4,
            death: 4,
            assist: 9,
            damage: 29836,
            gold: 13812,
          },
          {
            name: '뱅',
            champion: 'Ezreal',
            role: 'ADC',
            kill: 5,
            death: 2,
            assist: 7,
            damage: 45759,
            gold: 16257,
          },
          {
            name: '던',
            champion: 'Maokai',
            role: 'SUP',
            kill: 2,
            death: 8,
            assist: 11,
            damage: 10344,
            gold: 8653,
          },
        ],
        redTeam: [
          {
            name: '강소연',
            champion: 'Garen',
            role: 'TOP',
            kill: 8,
            death: 2,
            assist: 10,
            damage: 34182,
            gold: 16267,
          },
          {
            name: '네클릿',
            champion: 'XinZhao',
            role: 'JG',
            kill: 1,
            death: 6,
            assist: 11,
            damage: 29445,
            gold: 12685,
          },
          {
            name: '큐베',
            champion: 'Viktor',
            role: 'MID',
            kill: 4,
            death: 2,
            assist: 16,
            damage: 61948,
            gold: 15218,
          },
          {
            name: '크캣',
            champion: 'Caitlyn',
            role: 'ADC',
            kill: 11,
            death: 3,
            assist: 7,
            damage: 55756,
            gold: 18164,
          },
          {
            name: '루루카',
            champion: 'Milio',
            role: 'SUP',
            kill: 0,
            death: 3,
            assist: 22,
            damage: 5568,
            gold: 9523,
          },
        ],
      },
      {
        id: 's43',
        setNumber: 3,
        winner: '노코멘트',
        blueTeamBans: ['Draven', 'Vi', 'Lulu', 'Jinx', 'Nocturne'],
        redTeamBans: ['Varus', 'Gwen', 'MonkeyKing', 'Nasus', 'Darius'],
        blueTeamPicks: ['Seraphine', 'Lillia', 'Sivir', 'Sett', 'Ahri'],
        redTeamPicks: ['Tristana', 'Sion', 'Blitzcrank', 'JarvanIV', 'Corki'],
        blueTeamKills: 22,
        redTeamKills: 7,
        blueTeamDeath: 7,
        redTeamDeath: 22,
        blueTeamAsist: 64,
        redTeamAsist: 21,
        blueTeamGold: 57988,
        redTeamGold: 46345,
        duration: '29:07',
        blueTeam: [
          {
            name: '인섹',
            champion: 'Sett',
            role: 'TOP',
            kill: 3,
            death: 2,
            assist: 9,
            damage: 22863,
            gold: 13192,
          },
          {
            name: '고수달',
            champion: 'Lillia',
            role: 'JG',
            kill: 6,
            death: 1,
            assist: 13,
            damage: 19181,
            gold: 12051,
          },
          {
            name: '인간젤리',
            champion: 'Ahri',
            role: 'MID',
            kill: 4,
            death: 2,
            assist: 13,
            damage: 16759,
            gold: 10289,
          },
          {
            name: '뱅',
            champion: 'Sivir',
            role: 'ADC',
            kill: 6,
            death: 2,
            assist: 14,
            damage: 25953,
            gold: 13615,
          },
          {
            name: '던',
            champion: 'Seraphine',
            role: 'SUP',
            kill: 3,
            death: 0,
            assist: 15,
            damage: 5974,
            gold: 8841,
          },
        ],
        redTeam: [
          {
            name: '강소연',
            champion: 'Sion',
            role: 'TOP',
            kill: 0,
            death: 3,
            assist: 3,
            damage: 10348,
            gold: 8553,
          },
          {
            name: '네클릿',
            champion: 'JarvanIV',
            role: 'JG',
            kill: 1,
            death: 3,
            assist: 6,
            damage: 10718,
            gold: 9234,
          },
          {
            name: '큐베',
            champion: 'Corki',
            role: 'MID',
            kill: 3,
            death: 5,
            assist: 3,
            damage: 31936,
            gold: 11577,
          },
          {
            name: '크캣',
            champion: 'Tristana',
            role: 'ADC',
            kill: 3,
            death: 4,
            assist: 3,
            damage: 21208,
            gold: 10996,
          },
          {
            name: '루루카',
            champion: 'Blitzcrank',
            role: 'SUP',
            kill: 0,
            death: 7,
            assist: 6,
            damage: 4813,
            gold: 5985,
          },
        ],
      },
    ],
  },
  {
    id: 'm16',
    matchNumber: 16,
    blueTeam: '남성',
    redTeam: '노코멘트',
    blueTeamScore: 0,
    redTeamScore: 0,
    date: '2025-04-13',
    completed: false,
    progress: true,
    stage: '결승전',
    sets: [
      {
        id: 's44',
        setNumber: 1,
        winner: '',
        blueTeamBans: ['Ambessa', 'Ezreal', 'Yuumi', 'Xayah', 'Jinx'],
        redTeamBans: ['Vi', 'Hwei', 'Corki', 'Lillia', 'Rakan'],
        blueTeamPicks: ['Yone', 'Tristana', 'Singed', 'XinZhao', 'Nautilus'],
        redTeamPicks: ['Gwen', 'Sejuani', 'Taliyah', 'Lucian', 'Braum'],
        blueTeamKills: 0,
        redTeamKills: 0,
        blueTeamDeath: 0,
        redTeamDeath: 0,
        blueTeamAsist: 0,
        redTeamAsist: 0,
        blueTeamGold: 0,
        redTeamGold: 0,
        duration: '',
        blueTeam: [
          {
            name: '룩삼',
            champion: 'Singed',
            role: 'TOP',
            kill: 0,
            death: 0,
            assist: 0,
            damage: 0,
            gold: 0,
          },
          {
            name: '앰비션',
            champion: 'XinZhao',
            role: 'JG',
            kill: 0,
            death: 0,
            assist: 0,
            damage: 0,
            gold: 0,
          },
          {
            name: '실프',
            champion: 'Yone',
            role: 'MID',
            kill: 0,
            death: 0,
            assist: 0,
            damage: 0,
            gold: 0,
          },
          {
            name: '따효니',
            champion: 'Tristana',
            role: 'ADC',
            kill: 0,
            death: 0,
            assist: 0,
            damage: 0,
            gold: 0,
          },
          {
            name: '라콩',
            champion: 'Nautilus',
            role: 'SUP',
            kill: 0,
            death: 0,
            assist: 0,
            damage: 0,
            gold: 0,
          },
        ],
        redTeam: [
          {
            name: '인섹',
            champion: 'Gwen',
            role: 'TOP',
            kill: 0,
            death: 0,
            assist: 0,
            damage: 0,
            gold: 0,
          },
          {
            name: '고수달',
            champion: 'Sejuani',
            role: 'JG',
            kill: 0,
            death: 0,
            assist: 0,
            damage: 0,
            gold: 0,
          },
          {
            name: '인간젤리',
            champion: 'Taliyah',
            role: 'MID',
            kill: 0,
            death: 0,
            assist: 0,
            damage: 0,
            gold: 0,
          },
          {
            name: '뱅',
            champion: 'Lucian',
            role: 'ADC',
            kill: 0,
            death: 0,
            assist: 0,
            damage: 0,
            gold: 0,
          },
          {
            name: '던',
            champion: 'Braum',
            role: 'SUP',
            kill: 0,
            death: 0,
            assist: 0,
            damage: 0,
            gold: 0,
          },
        ],
      },
      {
        id: 's45',
        setNumber: 2,
        winner: '',
        blueTeamBans: [],
        redTeamBans: [],
        blueTeamPicks: [],
        redTeamPicks: [],
        blueTeamKills: 0,
        redTeamKills: 0,
        blueTeamDeath: 0,
        redTeamDeath: 0,
        blueTeamAsist: 0,
        redTeamAsist: 0,
        blueTeamGold: 0,
        redTeamGold: 0,
        duration: '',
        blueTeam: [
          {
            name: '룩삼',
            champion: '',
            role: 'TOP',
            kill: 0,
            death: 0,
            assist: 0,
            damage: 0,
            gold: 0,
          },
          {
            name: '앰비션',
            champion: '',
            role: 'JG',
            kill: 0,
            death: 0,
            assist: 0,
            damage: 0,
            gold: 0,
          },
          {
            name: '실프',
            champion: '',
            role: 'MID',
            kill: 0,
            death: 0,
            assist: 0,
            damage: 0,
            gold: 0,
          },
          {
            name: '따효니',
            champion: '',
            role: 'ADC',
            kill: 0,
            death: 0,
            assist: 0,
            damage: 0,
            gold: 0,
          },
          {
            name: '라콩',
            champion: '',
            role: 'SUP',
            kill: 0,
            death: 0,
            assist: 0,
            damage: 0,
            gold: 0,
          },
        ],
        redTeam: [
          {
            name: '인섹',
            champion: '',
            role: 'TOP',
            kill: 0,
            death: 0,
            assist: 0,
            damage: 0,
            gold: 0,
          },
          {
            name: '고수달',
            champion: '',
            role: 'JG',
            kill: 0,
            death: 0,
            assist: 0,
            damage: 0,
            gold: 0,
          },
          {
            name: '인간젤리',
            champion: '',
            role: 'MID',
            kill: 0,
            death: 0,
            assist: 0,
            damage: 0,
            gold: 0,
          },
          {
            name: '뱅',
            champion: '',
            role: 'ADC',
            kill: 0,
            death: 0,
            assist: 0,
            damage: 0,
            gold: 0,
          },
          {
            name: '던',
            champion: '',
            role: 'SUP',
            kill: 0,
            death: 0,
            assist: 0,
            damage: 0,
            gold: 0,
          },
        ],
      },
      {
        id: 's46',
        setNumber: 3,
        winner: '',
        blueTeamBans: [],
        redTeamBans: [],
        blueTeamPicks: [],
        redTeamPicks: [],
        blueTeamKills: 0,
        redTeamKills: 0,
        blueTeamDeath: 0,
        redTeamDeath: 0,
        blueTeamAsist: 0,
        redTeamAsist: 0,
        blueTeamGold: 0,
        redTeamGold: 0,
        duration: '',
        blueTeam: [
          {
            name: '룩삼',
            champion: '',
            role: 'TOP',
            kill: 0,
            death: 0,
            assist: 0,
            damage: 0,
            gold: 0,
          },
          {
            name: '앰비션',
            champion: '',
            role: 'JG',
            kill: 0,
            death: 0,
            assist: 0,
            damage: 0,
            gold: 0,
          },
          {
            name: '실프',
            champion: '',
            role: 'MID',
            kill: 0,
            death: 0,
            assist: 0,
            damage: 0,
            gold: 0,
          },
          {
            name: '따효니',
            champion: '',
            role: 'ADC',
            kill: 0,
            death: 0,
            assist: 0,
            damage: 0,
            gold: 0,
          },
          {
            name: '라콩',
            champion: '',
            role: 'SUP',
            kill: 0,
            death: 0,
            assist: 0,
            damage: 0,
            gold: 0,
          },
        ],
        redTeam: [
          {
            name: '인섹',
            champion: '',
            role: 'TOP',
            kill: 0,
            death: 0,
            assist: 0,
            damage: 0,
            gold: 0,
          },
          {
            name: '고수달',
            champion: '',
            role: 'JG',
            kill: 0,
            death: 0,
            assist: 0,
            damage: 0,
            gold: 0,
          },
          {
            name: '인간젤리',
            champion: '',
            role: 'MID',
            kill: 0,
            death: 0,
            assist: 0,
            damage: 0,
            gold: 0,
          },
          {
            name: '뱅',
            champion: '',
            role: 'ADC',
            kill: 0,
            death: 0,
            assist: 0,
            damage: 0,
            gold: 0,
          },
          {
            name: '던',
            champion: '',
            role: 'SUP',
            kill: 0,
            death: 0,
            assist: 0,
            damage: 0,
            gold: 0,
          },
        ],
      },
    ],
  },
]

export default playoffMatchData
